const mongoose = require("mongoose");
const diamondPurchaseSchema = new mongoose.Schema({
  grp: {type: String},
  no: {type: String},
  size: {type: String},
  ct: {type: String},
  sel_ct: {type: String},
  rate: {type: String},
  Less: {type: String},
  less: {type: String},
  base: {type: String},
  exp:{type: String, default: null},
  terms:{type: String, default: null},
  rij:{type: String, default: null},
  amt:{type: String, default: null},
  net_rd:{type: String, default: null},
  party:{type: String, default: null},
  Dalal: {type: String, default: null},
  Dalali:{type: String, default: null},
  add_less:{type: String, default: null},
  rd:{type: String, default: null},
  mark:{type: String, default: null},
  cls:{type: String, default: null},
  date:{type: Date, default: null},
  pay_date:{type: Date, default: null},
  due_date:{type: Date, default: null},
  receive_date:{type: Date, default: null},
});
module.exports = mongoose.model("diamond", diamondPurchaseSchema);
