const mongoose = require("mongoose");
const diamondExportSchema = new mongoose.Schema({
  no: {type: String},
  export: {type: String},
  total_purchase: {type: String},
  purchase_price: {type: String},
  total_sale: {type: String},
  sale_price: {type: String},
  exp:{type: String, default: null},
  terms:{type: String, default: null},
  purchase_rs:{type: String, default: null},
  sale_rs:{type: String, default: null},
  p_l:{type: String, default: null},
  diff_per_month:{type: String, default: null},
  purchase_party: {type: String, default: null},
  purchase_broker:{type: String, default: null},
  sale_party:{type: String, default: null},
  sale_broker:{type: String, default: null},
  export_party:{type: String, default: null},
  export_destination:{type: String, default: null},
  purchase_rd:{type: String, default: null},
  add_less:{type: String, default: null},
  sall_rd:{type: String, default: null},
  mark:{type: String, default: null},
  cls:{type: String, default: null},
  date:{type: Date, default: null},
  due_date:{type: Date, default: null},
  partner:{type: String, default: null},
  net_us:{type: String, default: null},
  int:{type: String, default: null},
  net_rd:{type: String, default: null},
  rd:{type: String, default: null},
  partner_rd:{type: String, default: null},
  int_jama:{type: String, default: null},
  amount:{type: String, default: null},
  booking:{type: String, default: null},
});
module.exports = mongoose.model("diamondexport", diamondExportSchema);
